
name: coffee-shop-analysis-system
networks:
  analysis_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24


services:
    rabbitmq:
        image: "rabbitmq:4.1.4-management"
        container_name: "rabbitmq"
        hostname: "rabbitmq"
        ports:
          - "5672:5672"
          - "15672:15672"
        networks:
          - analysis_net
        environment:
          RABBITMQ_DEFAULT_USER: user
          RABBITMQ_DEFAULT_PASS: user
        healthcheck:
          test: ["CMD", "rabbitmq-diagnostics", "ping"]
          interval: 10s
          timeout: 5s
          retries: 3
          start_period: 30s

    client-handler:
        container_name: "client-handler"
        depends_on:
          rabbitmq:
            condition: service_healthy
        networks:
          - analysis_net
        environment:
          RABBITMQ_HOST: rabbitmq
          RABBITMQ_PORT: 5672
          RABBITMQ_USER: user
          RABBITMQ_PASS: user
        hostname: "server"
        build:
          context: ./src/
          dockerfile: clientHandler/Dockerfile
        volumes:
          - ./src/clientHandler/config.yaml:/config.yaml 

    client1:
        container_name: "client1"
        environment:
          CLIENT_ID: "1"
          FILETYPES: "transactions,transaction_items,store,menu,users"
        depends_on:
          - client-handler
        networks:
          - analysis_net
        build:
          context: ./src/client
          dockerfile: Dockerfile
        volumes:
          - ./src/client/config.yaml:/config.yaml
          - ./src/client/results:/results
          - ./.data:/data

    filter-year1:
        container_name: "filter-year1"
        depends_on:
          rabbitmq:
            condition: service_healthy
        networks:
          - analysis_net
        environment:
          RABBITMQ_HOST: rabbitmq
          RABBITMQ_PORT: 5672
          RABBITMQ_USER: user
          RABBITMQ_PASS: user
          FILTER_TYPE: year
          FILTER_ID: -year1
          FILTER_COUNT: 1
        build:
          context: ./src/
          dockerfile: filters/Dockerfile
        volumes:
          - ./src/filters/config.yaml:/config.yaml 

    filter-hour1:
        container_name: "filter-hour1"
        depends_on:
          rabbitmq:
            condition: service_healthy
        networks:
          - analysis_net
        environment:
          RABBITMQ_HOST: rabbitmq
          RABBITMQ_PORT: 5672
          RABBITMQ_USER: user
          RABBITMQ_PASS: user
          FILTER_TYPE: hour
          FILTER_ID: -hour1
          FILTER_COUNT: 1
        build:
          context: ./src/
          dockerfile: filters/Dockerfile
        volumes:
          - ./src/filters/config.yaml:/config.yaml 

    filter-amount1:
        container_name: "filter-amount1"
        depends_on:
          rabbitmq:
            condition: service_healthy
        networks:
          - analysis_net
        environment:
          RABBITMQ_HOST: rabbitmq
          RABBITMQ_PORT: 5672
          RABBITMQ_USER: user
          RABBITMQ_PASS: user
          FILTER_TYPE: amount
          FILTER_ID: -amount1
          FILTER_COUNT: 1
        build:
          context: ./src/
          dockerfile: filters/Dockerfile
        volumes:
          - ./src/filters/config.yaml:/config.yaml 

    group-yearmonth1:
        container_name: "group-yearmonth1"
        depends_on:
          rabbitmq:
            condition: service_healthy
        networks:
          - analysis_net
        environment:
          RABBITMQ_HOST: rabbitmq
          RABBITMQ_PORT: 5672
          RABBITMQ_USER: user
          RABBITMQ_PASS: user
          GROUP_TYPE: yearmonth
          GROUP_ID: -yearmonth1
          GROUP_COUNT: 1
        build:
          context: ./src/
          dockerfile: group/Dockerfile
        volumes:
          - ./src/group/config.yaml:/config.yaml 

    group-semester1:
        container_name: "group-semester1"
        depends_on:
          rabbitmq:
            condition: service_healthy
        networks:
          - analysis_net
        environment:
          RABBITMQ_HOST: rabbitmq
          RABBITMQ_PORT: 5672
          RABBITMQ_USER: user
          RABBITMQ_PASS: user
          GROUP_TYPE: semester
          GROUP_ID: -semester1
          GROUP_COUNT: 1
        build:
          context: ./src/
          dockerfile: group/Dockerfile
        volumes:
          - ./src/group/config.yaml:/config.yaml 

    group-store1:
        container_name: "group-store1"
        depends_on:
          rabbitmq:
            condition: service_healthy
        networks:
          - analysis_net
        environment:
          RABBITMQ_HOST: rabbitmq
          RABBITMQ_PORT: 5672
          RABBITMQ_USER: user
          RABBITMQ_PASS: user
          GROUP_TYPE: store
          GROUP_ID: -store1
          GROUP_COUNT: 1
        build:
          context: ./src/
          dockerfile: group/Dockerfile
        volumes:
          - ./src/group/config.yaml:/config.yaml 

    join-items1:
        container_name: "join-items1"
        depends_on:
          rabbitmq:
            condition: service_healthy
        networks:
          - analysis_net
        environment:
          RABBITMQ_HOST: rabbitmq
          RABBITMQ_PORT: 5672
          RABBITMQ_USER: user
          RABBITMQ_PASS: user
          JOIN_TYPE: items
          JOIN_ID: -items1
          JOIN_COUNT: 1
        build:
          context: ./src/
          dockerfile: join/Dockerfile
        volumes:
          - ./src/join/config.yaml:/config.yaml 

    join-store1:
        container_name: "join-store1"
        depends_on:
          rabbitmq:
            condition: service_healthy
        networks:
          - analysis_net
        environment:
          RABBITMQ_HOST: rabbitmq
          RABBITMQ_PORT: 5672
          RABBITMQ_USER: user
          RABBITMQ_PASS: user
          JOIN_TYPE: store
          JOIN_ID: -store1
          JOIN_COUNT: 1
        build:
          context: ./src/
          dockerfile: join/Dockerfile
        volumes:
          - ./src/join/config.yaml:/config.yaml 

    join-users:
        container_name: "join-users"
        depends_on:
          rabbitmq:
            condition: service_healthy
        networks:
          - analysis_net
        environment:
          RABBITMQ_HOST: rabbitmq
          RABBITMQ_PORT: 5672
          RABBITMQ_USER: user
          RABBITMQ_PASS: user
          JOIN_TYPE: users
          JOIN_ID: -users
          JOIN_COUNT: 1
        build:
          context: ./src/
          dockerfile: join/Dockerfile
        volumes:
          - ./src/join/config.yaml:/config.yaml 

    topk1:
        container_name: "topk1"
        depends_on:
          rabbitmq:
            condition: service_healthy
        networks:
          - analysis_net
        environment:
          RABBITMQ_HOST: rabbitmq
          RABBITMQ_PORT: 5672
          RABBITMQ_USER: user
          RABBITMQ_PASS: user
          TOTAL_TOPS = 1
        build:
          context: ./src/
          dockerfile: topk/Dockerfile
        volumes:
          - ./src/topk/config.yaml:/config.yaml
