
name: coffee-shop-analysis-system
networks:
  analysis_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24


services:
    rabbitmq:
        image: "rabbitmq:4.1.4-management"
        container_name: "rabbitmq"
        hostname: "rabbitmq"
        ports:
          - "5672:5672"
          - "15672:15672"
        networks:
          - analysis_net
        environment:
          RABBITMQ_DEFAULT_USER: user
          RABBITMQ_DEFAULT_PASS: user
        healthcheck:
          test: ["CMD", "rabbitmq-diagnostics", "ping"]
          interval: 10s
          timeout: 5s
          retries: 3
          start_period: 30s

    client_handler:
        container_name: "client-handler"
        depends_on:
          rabbitmq:
            condition: service_healthy
        networks:
          - analysis_net
        hostname: "server"
        build:
          context: ./src/clientHandler
          dockerfile: Dockerfile
        volumes:
          - ./src/clientHandler/config.yaml:/config.yaml 

    client1:
        container_name: "client1"
        environment:
          CLIENT_ID: "1"
          FILETYPES: "transactions,transaction_items,stores,menu,users"
        depends_on:
          - client_handler
        networks:
          - analysis_net
        build:
          context: ./src/client
          dockerfile: Dockerfile
        volumes:
          - ./src/client/config.yaml:/config.yaml
          - ./.data:/data
