
name: coffee-shop-analysis-system
networks:
  analysis_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24


services:
    rabbitmq:
        image: "rabbitmq:4.1.4-management"
        container_name: "rabbitmq"
        hostname: "rabbitmq"
        ports:
          - "5672:5672"
          - "15672:15672"
        networks:
          - analysis_net
        environment:
          RABBITMQ_DEFAULT_USER: user
          RABBITMQ_DEFAULT_PASS: user
        healthcheck:
          test: ["CMD", "rabbitmq-diagnostics", "ping"]
          interval: 10s
          timeout: 5s
          retries: 3
          start_period: 30s

    client-handler:
        container_name: "client-handler"
        depends_on:
          rabbitmq:
            condition: service_healthy
        networks:
          - analysis_net
        environment:
          RABBITMQ_HOST: rabbitmq
          RABBITMQ_PORT: 5672
          RABBITMQ_USER: user
          RABBITMQ_PASS: user
        hostname: "server"
        build:
          context: ./src/
          dockerfile: clientHandler/Dockerfile
        volumes:
          - ./src/clientHandler/config.yaml:/config.yaml 

    client1:
        container_name: "client1"
        environment:
          CLIENT_ID: "1"
          FILETYPES: "transactions,transaction_items,stores,menu,users"
        depends_on:
          - client-handler
        networks:
          - analysis_net
        build:
          context: ./src/client
          dockerfile: Dockerfile
        volumes:
          - ./src/client/config.yaml:/config.yaml
          - ./.data:/data

    filter-year1:
        container_name: "filter-year1"
        depends_on:
          rabbitmq:
            condition: service_healthy
        networks:
          - analysis_net
        environment:
          RABBITMQ_HOST: rabbitmq
          RABBITMQ_PORT: 5672
          RABBITMQ_USER: user
          RABBITMQ_PASS: user
          FILTER_TYPE: year
          FILTER_ID: -year1
          FILTER_COUNT: 1
        build:
          context: ./src/
          dockerfile: filters/Dockerfile
        volumes:
          - ./src/filters/config.yaml:/config.yaml 

    filter-hour1:
        container_name: "filter-hour1"
        depends_on:
          rabbitmq:
            condition: service_healthy
        networks:
          - analysis_net
        environment:
          RABBITMQ_HOST: rabbitmq
          RABBITMQ_PORT: 5672
          RABBITMQ_USER: user
          RABBITMQ_PASS: user
          FILTER_TYPE: hour
          FILTER_ID: -hour1
          FILTER_COUNT: 1
        build:
          context: ./src/
          dockerfile: filters/Dockerfile
        volumes:
          - ./src/filters/config.yaml:/config.yaml 

    filter-amount1:
        container_name: "filter-amount1"
        depends_on:
          rabbitmq:
            condition: service_healthy
        networks:
          - analysis_net
        environment:
          RABBITMQ_HOST: rabbitmq
          RABBITMQ_PORT: 5672
          RABBITMQ_USER: user
          RABBITMQ_PASS: user
          FILTER_TYPE: amount
          FILTER_ID: -amount1
          FILTER_COUNT: 1
        build:
          context: ./src/
          dockerfile: filters/Dockerfile
        volumes:
          - ./src/filters/config.yaml:/config.yaml 

    group-yearmonth1:
        container_name: "group-yearmonth1"
        depends_on:
          rabbitmq:
            condition: service_healthy
        networks:
          - analysis_net
        environment:
          RABBITMQ_HOST: rabbitmq
          RABBITMQ_PORT: 5672
          RABBITMQ_USER: user
          RABBITMQ_PASS: user
          GROUP_TYPE: yearmonth
          GROUP_ID: -yearmonth1
          GROUP_COUNT: 1
        build:
          context: ./src/
          dockerfile: group/Dockerfile
        volumes:
          - ./src/group/config.yaml:/config.yaml 
