
name: coffee-shop-analysis-system
networks:
  analysis_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24


services:
    rabbitmq:
        image: "rabbitmq:4.1.4-management"
        container_name: "rabbitmq"
        hostname: "rabbitmq"
        ports:
          - "5672:5672"
          - "15672:15672"
        networks:
          - analysis_net
        environment:
          RABBITMQ_DEFAULT_USER: user
          RABBITMQ_DEFAULT_PASS: user
        healthcheck:
          test: ["CMD", "rabbitmq-diagnostics", "ping"]
          interval: 10s
          timeout: 5s
          retries: 3
          start_period: 30s

    client-handler:
        container_name: "client-handler"
        depends_on:
          rabbitmq:
            condition: service_healthy
        networks:
          - analysis_net
        environment:
          RABBITMQ_HOST: rabbitmq
          RABBITMQ_PORT: 5672
          RABBITMQ_USER: user
          RABBITMQ_PASS: user
        hostname: "server"
        build:
          context: ./src/
          dockerfile: clientHandler/Dockerfile
        volumes:
          - ./src/clientHandler/config.yaml:/config.yaml 

    client1:
        container_name: "client1"
        environment:
          CLIENT_ID: "1"
          FILETYPES: "stores,menu,users,transactions,transaction_items,"
        depends_on:
          - client-handler
        networks:
          - analysis_net
        build:
          context: ./src/client
          dockerfile: Dockerfile
        volumes:
          - ./src/client/config.yaml:/config.yaml
          - ./.data:/data

    filter-year1:
        container_name: "filter-year1"
        depends_on:
          rabbitmq:
            condition: service_healthy
        networks:
          - analysis_net
        environment:
          RABBITMQ_HOST: rabbitmq
          RABBITMQ_PORT: 5672
          RABBITMQ_USER: user
          RABBITMQ_PASS: user
          FILTER_TYPE: year
          FILTER_ID: -year1
          FILTER_COUNT: 5
        build:
          context: ./src/
          dockerfile: filters/Dockerfile
        volumes:
          - ./src/filters/config.yaml:/config.yaml 

    filter-year2:
        container_name: "filter-year2"
        depends_on:
          rabbitmq:
            condition: service_healthy
        networks:
          - analysis_net
        environment:
          RABBITMQ_HOST: rabbitmq
          RABBITMQ_PORT: 5672
          RABBITMQ_USER: user
          RABBITMQ_PASS: user
          FILTER_TYPE: year
          FILTER_ID: -year2
          FILTER_COUNT: 5
        build:
          context: ./src/
          dockerfile: filters/Dockerfile
        volumes:
          - ./src/filters/config.yaml:/config.yaml 

    filter-year3:
        container_name: "filter-year3"
        depends_on:
          rabbitmq:
            condition: service_healthy
        networks:
          - analysis_net
        environment:
          RABBITMQ_HOST: rabbitmq
          RABBITMQ_PORT: 5672
          RABBITMQ_USER: user
          RABBITMQ_PASS: user
          FILTER_TYPE: year
          FILTER_ID: -year3
          FILTER_COUNT: 5
        build:
          context: ./src/
          dockerfile: filters/Dockerfile
        volumes:
          - ./src/filters/config.yaml:/config.yaml 

    filter-year4:
        container_name: "filter-year4"
        depends_on:
          rabbitmq:
            condition: service_healthy
        networks:
          - analysis_net
        environment:
          RABBITMQ_HOST: rabbitmq
          RABBITMQ_PORT: 5672
          RABBITMQ_USER: user
          RABBITMQ_PASS: user
          FILTER_TYPE: year
          FILTER_ID: -year4
          FILTER_COUNT: 5
        build:
          context: ./src/
          dockerfile: filters/Dockerfile
        volumes:
          - ./src/filters/config.yaml:/config.yaml 

    filter-year5:
        container_name: "filter-year5"
        depends_on:
          rabbitmq:
            condition: service_healthy
        networks:
          - analysis_net
        environment:
          RABBITMQ_HOST: rabbitmq
          RABBITMQ_PORT: 5672
          RABBITMQ_USER: user
          RABBITMQ_PASS: user
          FILTER_TYPE: year
          FILTER_ID: -year5
          FILTER_COUNT: 5
        build:
          context: ./src/
          dockerfile: filters/Dockerfile
        volumes:
          - ./src/filters/config.yaml:/config.yaml 

    filter-hour1:
        container_name: "filter-hour1"
        depends_on:
          rabbitmq:
            condition: service_healthy
        networks:
          - analysis_net
        environment:
          RABBITMQ_HOST: rabbitmq
          RABBITMQ_PORT: 5672
          RABBITMQ_USER: user
          RABBITMQ_PASS: user
          FILTER_TYPE: hour
          FILTER_ID: -hour1
          FILTER_COUNT: 5
        build:
          context: ./src/
          dockerfile: filters/Dockerfile
        volumes:
          - ./src/filters/config.yaml:/config.yaml 

    filter-hour2:
        container_name: "filter-hour2"
        depends_on:
          rabbitmq:
            condition: service_healthy
        networks:
          - analysis_net
        environment:
          RABBITMQ_HOST: rabbitmq
          RABBITMQ_PORT: 5672
          RABBITMQ_USER: user
          RABBITMQ_PASS: user
          FILTER_TYPE: hour
          FILTER_ID: -hour2
          FILTER_COUNT: 5
        build:
          context: ./src/
          dockerfile: filters/Dockerfile
        volumes:
          - ./src/filters/config.yaml:/config.yaml 

    filter-hour3:
        container_name: "filter-hour3"
        depends_on:
          rabbitmq:
            condition: service_healthy
        networks:
          - analysis_net
        environment:
          RABBITMQ_HOST: rabbitmq
          RABBITMQ_PORT: 5672
          RABBITMQ_USER: user
          RABBITMQ_PASS: user
          FILTER_TYPE: hour
          FILTER_ID: -hour3
          FILTER_COUNT: 5
        build:
          context: ./src/
          dockerfile: filters/Dockerfile
        volumes:
          - ./src/filters/config.yaml:/config.yaml 

    filter-hour4:
        container_name: "filter-hour4"
        depends_on:
          rabbitmq:
            condition: service_healthy
        networks:
          - analysis_net
        environment:
          RABBITMQ_HOST: rabbitmq
          RABBITMQ_PORT: 5672
          RABBITMQ_USER: user
          RABBITMQ_PASS: user
          FILTER_TYPE: hour
          FILTER_ID: -hour4
          FILTER_COUNT: 5
        build:
          context: ./src/
          dockerfile: filters/Dockerfile
        volumes:
          - ./src/filters/config.yaml:/config.yaml 

    filter-hour5:
        container_name: "filter-hour5"
        depends_on:
          rabbitmq:
            condition: service_healthy
        networks:
          - analysis_net
        environment:
          RABBITMQ_HOST: rabbitmq
          RABBITMQ_PORT: 5672
          RABBITMQ_USER: user
          RABBITMQ_PASS: user
          FILTER_TYPE: hour
          FILTER_ID: -hour5
          FILTER_COUNT: 5
        build:
          context: ./src/
          dockerfile: filters/Dockerfile
        volumes:
          - ./src/filters/config.yaml:/config.yaml 

    filter-amount1:
        container_name: "filter-amount1"
        depends_on:
          rabbitmq:
            condition: service_healthy
        networks:
          - analysis_net
        environment:
          RABBITMQ_HOST: rabbitmq
          RABBITMQ_PORT: 5672
          RABBITMQ_USER: user
          RABBITMQ_PASS: user
          FILTER_TYPE: amount
          FILTER_ID: -amount1
          FILTER_COUNT: 5
        build:
          context: ./src/
          dockerfile: filters/Dockerfile
        volumes:
          - ./src/filters/config.yaml:/config.yaml 

    filter-amount2:
        container_name: "filter-amount2"
        depends_on:
          rabbitmq:
            condition: service_healthy
        networks:
          - analysis_net
        environment:
          RABBITMQ_HOST: rabbitmq
          RABBITMQ_PORT: 5672
          RABBITMQ_USER: user
          RABBITMQ_PASS: user
          FILTER_TYPE: amount
          FILTER_ID: -amount2
          FILTER_COUNT: 5
        build:
          context: ./src/
          dockerfile: filters/Dockerfile
        volumes:
          - ./src/filters/config.yaml:/config.yaml 

    filter-amount3:
        container_name: "filter-amount3"
        depends_on:
          rabbitmq:
            condition: service_healthy
        networks:
          - analysis_net
        environment:
          RABBITMQ_HOST: rabbitmq
          RABBITMQ_PORT: 5672
          RABBITMQ_USER: user
          RABBITMQ_PASS: user
          FILTER_TYPE: amount
          FILTER_ID: -amount3
          FILTER_COUNT: 5
        build:
          context: ./src/
          dockerfile: filters/Dockerfile
        volumes:
          - ./src/filters/config.yaml:/config.yaml 

    filter-amount4:
        container_name: "filter-amount4"
        depends_on:
          rabbitmq:
            condition: service_healthy
        networks:
          - analysis_net
        environment:
          RABBITMQ_HOST: rabbitmq
          RABBITMQ_PORT: 5672
          RABBITMQ_USER: user
          RABBITMQ_PASS: user
          FILTER_TYPE: amount
          FILTER_ID: -amount4
          FILTER_COUNT: 5
        build:
          context: ./src/
          dockerfile: filters/Dockerfile
        volumes:
          - ./src/filters/config.yaml:/config.yaml 

    filter-amount5:
        container_name: "filter-amount5"
        depends_on:
          rabbitmq:
            condition: service_healthy
        networks:
          - analysis_net
        environment:
          RABBITMQ_HOST: rabbitmq
          RABBITMQ_PORT: 5672
          RABBITMQ_USER: user
          RABBITMQ_PASS: user
          FILTER_TYPE: amount
          FILTER_ID: -amount5
          FILTER_COUNT: 5
        build:
          context: ./src/
          dockerfile: filters/Dockerfile
        volumes:
          - ./src/filters/config.yaml:/config.yaml 

    group-yearmonth1:
        container_name: "group-yearmonth1"
        depends_on:
          rabbitmq:
            condition: service_healthy
        networks:
          - analysis_net
        environment:
          RABBITMQ_HOST: rabbitmq
          RABBITMQ_PORT: 5672
          RABBITMQ_USER: user
          RABBITMQ_PASS: user
          GROUP_TYPE: yearmonth
          GROUP_ID: -yearmonth1
          GROUP_COUNT: 5
        build:
          context: ./src/
          dockerfile: group/Dockerfile
        volumes:
          - ./src/group/config.yaml:/config.yaml 

    group-yearmonth2:
        container_name: "group-yearmonth2"
        depends_on:
          rabbitmq:
            condition: service_healthy
        networks:
          - analysis_net
        environment:
          RABBITMQ_HOST: rabbitmq
          RABBITMQ_PORT: 5672
          RABBITMQ_USER: user
          RABBITMQ_PASS: user
          GROUP_TYPE: yearmonth
          GROUP_ID: -yearmonth2
          GROUP_COUNT: 5
        build:
          context: ./src/
          dockerfile: group/Dockerfile
        volumes:
          - ./src/group/config.yaml:/config.yaml 

    group-yearmonth3:
        container_name: "group-yearmonth3"
        depends_on:
          rabbitmq:
            condition: service_healthy
        networks:
          - analysis_net
        environment:
          RABBITMQ_HOST: rabbitmq
          RABBITMQ_PORT: 5672
          RABBITMQ_USER: user
          RABBITMQ_PASS: user
          GROUP_TYPE: yearmonth
          GROUP_ID: -yearmonth3
          GROUP_COUNT: 5
        build:
          context: ./src/
          dockerfile: group/Dockerfile
        volumes:
          - ./src/group/config.yaml:/config.yaml 

    group-yearmonth4:
        container_name: "group-yearmonth4"
        depends_on:
          rabbitmq:
            condition: service_healthy
        networks:
          - analysis_net
        environment:
          RABBITMQ_HOST: rabbitmq
          RABBITMQ_PORT: 5672
          RABBITMQ_USER: user
          RABBITMQ_PASS: user
          GROUP_TYPE: yearmonth
          GROUP_ID: -yearmonth4
          GROUP_COUNT: 5
        build:
          context: ./src/
          dockerfile: group/Dockerfile
        volumes:
          - ./src/group/config.yaml:/config.yaml 

    group-yearmonth5:
        container_name: "group-yearmonth5"
        depends_on:
          rabbitmq:
            condition: service_healthy
        networks:
          - analysis_net
        environment:
          RABBITMQ_HOST: rabbitmq
          RABBITMQ_PORT: 5672
          RABBITMQ_USER: user
          RABBITMQ_PASS: user
          GROUP_TYPE: yearmonth
          GROUP_ID: -yearmonth5
          GROUP_COUNT: 5
        build:
          context: ./src/
          dockerfile: group/Dockerfile
        volumes:
          - ./src/group/config.yaml:/config.yaml 

    group-semester1:
        container_name: "group-semester1"
        depends_on:
          rabbitmq:
            condition: service_healthy
        networks:
          - analysis_net
        environment:
          RABBITMQ_HOST: rabbitmq
          RABBITMQ_PORT: 5672
          RABBITMQ_USER: user
          RABBITMQ_PASS: user
          GROUP_TYPE: semester
          GROUP_ID: -semester1
<<<<<<< Updated upstream
          GROUP_COUNT: 1
=======
          GROUP_COUNT: 5
>>>>>>> Stashed changes
        build:
          context: ./src/
          dockerfile: group/Dockerfile
        volumes:
          - ./src/group/config.yaml:/config.yaml 

    group-store1:
        container_name: "group-store1"
        depends_on:
          rabbitmq:
            condition: service_healthy
        networks:
          - analysis_net
        environment:
          RABBITMQ_HOST: rabbitmq
          RABBITMQ_PORT: 5672
          RABBITMQ_USER: user
          RABBITMQ_PASS: user
<<<<<<< Updated upstream
          GROUP_TYPE: store
          GROUP_ID: -store1
          GROUP_COUNT: 1
=======
          GROUP_TYPE: semester
          GROUP_ID: -semester2
          GROUP_COUNT: 5
>>>>>>> Stashed changes
        build:
          context: ./src/
          dockerfile: group/Dockerfile
        volumes:
          - ./src/group/config.yaml:/config.yaml 

    join-items1:
        container_name: "join-items1"
        depends_on:
          rabbitmq:
            condition: service_healthy
        networks:
          - analysis_net
        environment:
          RABBITMQ_HOST: rabbitmq
          RABBITMQ_PORT: 5672
          RABBITMQ_USER: user
          RABBITMQ_PASS: user
          GROUP_TYPE: semester
          GROUP_ID: -semester3
          GROUP_COUNT: 5
        build:
          context: ./src/
          dockerfile: join/Dockerfile
        volumes:
          - ./src/group/config.yaml:/config.yaml 

    group-semester4:
        container_name: "group-semester4"
        depends_on:
          rabbitmq:
            condition: service_healthy
        networks:
          - analysis_net
        environment:
          RABBITMQ_HOST: rabbitmq
          RABBITMQ_PORT: 5672
          RABBITMQ_USER: user
          RABBITMQ_PASS: user
          GROUP_TYPE: semester
          GROUP_ID: -semester4
          GROUP_COUNT: 5
        build:
          context: ./src/
          dockerfile: group/Dockerfile
        volumes:
          - ./src/group/config.yaml:/config.yaml 

    group-semester5:
        container_name: "group-semester5"
        depends_on:
          rabbitmq:
            condition: service_healthy
        networks:
          - analysis_net
        environment:
          RABBITMQ_HOST: rabbitmq
          RABBITMQ_PORT: 5672
          RABBITMQ_USER: user
          RABBITMQ_PASS: user
          GROUP_TYPE: semester
          GROUP_ID: -semester5
          GROUP_COUNT: 5
        build:
          context: ./src/
          dockerfile: group/Dockerfile
        volumes:
          - ./src/group/config.yaml:/config.yaml 

    join-items1:
        container_name: "join-items1"
        depends_on:
          rabbitmq:
            condition: service_healthy
        networks:
          - analysis_net
        environment:
          RABBITMQ_HOST: rabbitmq
          RABBITMQ_PORT: 5672
          RABBITMQ_USER: user
          RABBITMQ_PASS: user
          JOIN_TYPE: items
          JOIN_ID: -items1
          JOIN_COUNT: 2
        build:
          context: ./src/
          dockerfile: join/Dockerfile
        volumes:
          - ./src/join/config.yaml:/config.yaml 

    join-items2:
        container_name: "join-items2"
        depends_on:
          rabbitmq:
            condition: service_healthy
        networks:
          - analysis_net
        environment:
          RABBITMQ_HOST: rabbitmq
          RABBITMQ_PORT: 5672
          RABBITMQ_USER: user
          RABBITMQ_PASS: user
          JOIN_TYPE: items
          JOIN_ID: -items2
          JOIN_COUNT: 2
        build:
          context: ./src/
          dockerfile: join/Dockerfile
        volumes:
          - ./src/join/config.yaml:/config.yaml 
