group:
log:
  level: "INFO"
k: 35
watchMesh:
  heartbeatIntervalSeconds: 2.0
  heartbeatTimeoutSeconds: 10.0
  addressResolvingRetries: 3
  addressResolvingIntervalSeconds: 1.0
  showHeartbeatLogs: true
