filter:
  query1:
    fromYear: 2024
    toYear: 2025
    fromHour: 6
    toHour: 23
  query2:
    fromYear: 2024
    toYear: 2025
  query3:
    fromYear: 2024
    toYear: 2025
    fromHour: 6
    toHour: 23
  query4:
    fromYear: 2024
    toYear: 2025
log:
  level: "INFO"
